### ISSUE TITLE
Custom Slot Types don't appear in Alexa Tester

### ISSUE THREAD

**Issue by jradwan** [alexa-js/alexa-app#114]
Not sure what I'm missing and if this is a problem with alexa-app or alexa-app-server.

Trying to use a custom slot type, which basically looks like this in my intent:

```
    {
        "slots":{"COMMAND":"COMMAND_SLOT"},
        "utterances":[ "send {the|} {command|} {commands|COMMAND}" ]
    }
```
(where commands is an app.dictionary)

I've also tried:

```
    {
        "slots":{"COMMAND":"COMMAND_SLOT"},
        "utterances":[ "send {the|} {command|} {-|COMMAND}" ]
    }
```

In both cases, the Utterances properly appear in the Alexa Tester (using alexa-app-server 2.3.1), but the Custom Slot Type section of the tester is always empty. I was under the impression the custom slot type info should appear there to facilitate copy/pasting into the interaction model.

I started on alexa-app 2.3.4 and upgraded to 2.4.0 ... same problem.

Thanks!

**Comment by dblock** [comment]
It's probably a bug and I think it belongs in alexa-app-server, so feel free to move this there?

**Comment by jradwan** [comment]
Ok, done ([here](https://github.com/matt-kruse/alexa-app-server/issues/24)). Thanks!

**Comment by dblock** [comment]
I'll close this one.

**Comment by tejashah88** [comment]
I think it's safe to re-open this issue at this point, since it is a problem with `alexa-app`, not `alexa-app-server`.

**Comment by dblock** [comment]
Done.

**Comment by dblock** [comment]
This was basically unimplemented, PRs welcome.

**Comment by dblock** [comment]
Closed via https://github.com/alexa-js/alexa-app/pull/275, please try it out!
