### ISSUE TITLE
enableDebug=true is not able to render the debugger 

### ISSUE THREAD

**Issue by smaheshw** [alexa-js/alexa-app#121]
If I use following line of code : 
app.express(express_app, "", true);

I am using 2.4.0 version of alexa-app
 
This is the error thrown while opening the debugger in browser :

378| \t\t\t};\n    379| \t\t\t// Extract the applicationId if it exists and update the templates\n >> 380| \t\t\tvar applicationId = \"<%= app.id || \"\" %>\";\n    381| \t\t\tif (applicationId) {\n    382| \t\t\t\t$scope.templates.launch.session.application.applicationId = applicationId;\n    383| \t\t\t\t$scope.templates.intent.session.application.applicationId = applicationId;\n\napp is not defined\n

**Comment by dblock** [comment]
Is this problem in [alexa-app-server](https://github.com/alexa-js/alexa-app-server)? If so would you please open it there - and if you have a moment try to write a test for it and maybe a fix?

**Comment by dblock** [comment]
This has been fixed by a combination of #150 and changes in alexa-app-server. The next version, 2.5.0 of alexa-app and (probably 2.4.0 or 2.5.0) of alexa-app-server, will work.
