### ISSUE TITLE
res.say() doesn't work when in .then() of returned promise.

### ISSUE THREAD

**Issue by chearmstrong** [alexa-js/alexa-app#122]
I have something like this:

```
    alexaApp.intent('fooIntent', {
        'slots': {
          'foo': 'footype'
        },
        'utterances': [
          'my {name is|name\'s} {-|foo}'
        ]
      },
      function (req, res) {

       // If I put a .say() here, it works.

       bar()
            .then(something => {
              console.log(something);
              // This .say() doesn't work here
              res.say('something has been done');
            })
            .catch(err => {
              res.say('error' + err);
              throw err;
            });
      }
    );
```

The issue I have is that while in the .then() the .say() doesn't work... the console.log() works fine though, with the response I expect. However, if I do a .say() before this function, it works just fine.

It's got me stumped... Any ideas?

**Comment by chearmstrong** [comment]
Apologies... I've sorted it by following the Asynchronous Intent Handler in the read me.

**Comment by dblock** [comment]
There has been some conversation in https://github.com/alexa-js/alexa-app/issues/71 where a handler should just return a promise and then we don't have to do the whole `return false` thing. PRs welcome.
