### ISSUE TITLE
Scope problem?

### ISSUE THREAD

**Issue by OpenDog** [alexa-js/alexa-app#124]
In this snippet, the function keeps calling itself ```this.request```, not the ```new alexa.request``` and the recursion chews up the stack. When I rename the function to alexa.handleRequest, it works. What am I doing wrong? I'm on node 6.3. 

```
  this.request = function(request_json) {
    return new Promise(function(resolve, reject) {
      var request = new alexa.request(request_json);
      var response = new alexa.response(request.getSession());
      var postExecuted = false;
```

**Comment by dblock** [comment]
And what is `alexa`? Do you think you can turn this into a test?

**Comment by OpenDog** [comment]
Sorry this is a snippet from the index.js of the alexa-app package.

**Comment by dblock** [comment]
I see what you mean. But we do `var alexa = {};` right on top, so I don't see why this would call itself. Maybe want to show us a repro?

**Comment by OpenDog** [comment]
It's public: https://github.com/bespoken/xplatform-server

I'll try to create a shorter test.

**Comment by dblock** [comment]
Is this new in 2.4.0 and used to work?

**Comment by OpenDog** [comment]
I have not upgraded to the latest because of the session object changes. I'm on 2.3.4. But I looked into the latest and It seems the this part (express handler hookup) didn't change.

**Comment by OpenDog** [comment]
Ok. Here is an easy test.

https://github.com/OpenDog/alexa-test.git

**Comment by dblock** [comment]
You forgot a `new`, fix in https://github.com/OpenDog/alexa-test/pull/1. 

It took me a while to wrap my head around it. I am not sure whether we can do something in our code to make it easier to spot this.

**Comment by OpenDog** [comment]
Dang! You are right! Thanks a lot! Knowing how lazy I am I may have copy-pasted one of the examples. I'll double-check it!

**Comment by OpenDog** [comment]
I checked the docs and the examples. The "new" is there. My apologies. Thank you again for your help!

**Comment by dblock** [comment]
No problem!

**Comment by OpenDog** [comment]
This what you can do

```
alexa.app = function(name, endpoint) {
  "use strict"

  if (!(this instanceof alexa.app)) {
      throw new Error("Function needs to be called with the new keyword");
  }
```

**Comment by dblock** [comment]
@OpenDog that sounds great, would you be so kind to try to write a test for it and make a pull request?
