### ISSUE TITLE
The requested skill took too long to respond

### ISSUE THREAD

**Issue by scifutures** [alexa-js/alexa-app#130]
I get this "the requested skill took too long to respond" error from Alexa after having her say everything, but the user not saying something.  

```
res.say(say).reprompt(reprompt).shouldEndSession(false);
res.send()
```

I'm not sure how to either keep the session going longer or to have her timeout silently. Is there something I can do differently? Thanks.

**Comment by dblock** [comment]
Can you show us more code? I think your skill is actually getting a request and then hanging without responding. Are you returning `false` signaling some async operation?

**Comment by scifutures** [comment]
Yes, returning false for any async operations.  This seems to happen whether or not there were any async operations.  Alexa will say the response, say the reprompt, wait for what seems to be 5-8 seconds, and then timeout.  Sometimes the timeout is the lights on the top of the Echo flashing, sometimes the timeout is the error above, "the requested skill took too long to respond".

**Comment by scifutures** [comment]
This can be solved by checking the type of request in app 

```
app.pre = function(req, res, type) {
	if (req.data.request.type === 'SessionEndedRequest') {
		res.send('').shouldEndSession(true);
		return true;
	}
}
```
