### ISSUE TITLE
app.launch not being triggered

### ISSUE THREAD

**Issue by ldeluca** [alexa-js/alexa-app#131]
This could be an issue with my environment.  I'm using IBM Bluemix (cloudfoundry Diego) for my alexa-app.  I have app.pre which triggers just fine but app.launch is never called.  I get a response from Alexa (almost immediately) when I ask to open the skill.  Same is true for the dummy intent.  I used the simple use case from the example code just to get it working before adding my logic.

`There was an error calling the remote endpoint, which returned HTTP 500 : Internal Server Error`

**Comment by dblock** [comment]
You should debug this, ideally by reproducing it locally with an identical request - there should be a server-side error somewhere that shows what the issue is.

**Comment by dblock** [comment]
What was the issue @ldeluca ?

**Comment by ldeluca** [comment]
No idea, I ended up copying the example from the folder and started from there.  got it working. never did figure out what was wrong with the other code (which was also super simple).
