### ISSUE TITLE
Wrong behavior on AudioPlayer request error

### ISSUE THREAD

**Issue by fremail** [alexa-js/alexa-app#135]
By default it does `say` on exception, it's OK for Launch and intent requests, but isn't suitable for AudioPlayer requests.

[Amazon doc](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/custom-audioplayer-interface-reference#audioplayer-requests):
> When responding to AudioPlayer requests, you can only respond with AudioPlayer directives. The response cannot include any of the standard properties such as outputSpeech.

**Comment by fremail** [comment]
I don't have any idea what we could use instead of `say` in that case. 
`response.fail` seems too strict. Maybe log the error by `console.error` and send an empty response?
@dblock what do you think?

**Comment by dblock** [comment]
I feel like that should hard fail with an HTTP code. In the other scenarios we are able to communicate the error to the user and not fail the call, but in the audio one doing nothing seems to be the worst case, no?

**Comment by fremail** [comment]
Ending without any request causes an error in Alexa.
An empty answer (just `response.send()`) is a common case. Alexa works fine with it.
Didn't try `response.fail()`, but I suppose it causes an error in Alexa too. If it's so, I agree to fail the response. But I don't have a device to test it :(

**Comment by dblock** [comment]
Closed via https://github.com/alexa-js/alexa-app/pull/141.
