### ISSUE TITLE
Add section for which node versions are supported

### ISSUE THREAD

**Issue by tejashah88** [alexa-js/alexa-app#143]
If we plan to make any breaking changes that could potentially drop support for older versions of node, it's best to add a section in the README stating which versions **are** supported.

**Comment by mreinstein** [comment]
I would suggest just using the `engines` field in `package.json`

**Comment by mreinstein** [comment]
https://docs.npmjs.com/files/package.json#engines

**Comment by dblock** [comment]
If anyone wants to comment/merge https://github.com/alexa-js/alexa-app/pull/153, please.
