### ISSUE TITLE
Test hangs in verifier

### ISSUE THREAD

**Issue by dblock** [alexa-js/alexa-app#152]
This test hangs for no reason: https://github.com/dblock/alexa-app/blob/test-hangs/test/test_alexa_verifier_middleware_hangs.js, the middleware never fires `on('end', function() { })`, not sure what's going on.

**Comment by dblock** [comment]
@mreinstein you might be able to explain this one, I'm probably missing something obvious

**Comment by dblock** [comment]
So ... we need a body parser after the middleware. Does this mean https://github.com/alexa-js/alexa-app/pull/155?

**Comment by mreinstein** [comment]
the alexa-verifier-middleware already effectively acts like a JSON body parser. see: https://github.com/alexa-js/alexa-verifier-middleware/blob/master/index.js#L31

I think the logic should be:

```
if(checkCert) {
  install middleware
} else {
  install regular json body parser
}
```

the `if` clause is already implemented. just need the `else`

**Comment by dblock** [comment]
Ok, cool, updated. 

I am also *not* moving body-parser into dependencies just like we do with express. I assume this is correct?

**Comment by mreinstein** [comment]
> I am also not moving body-parser

if the code is using `body-parser` why would it not be a dependency?

**Comment by dblock** [comment]
We only use it in the express scenario, but you're right.
