### ISSUE TITLE
default value of slot

### ISSUE THREAD

**Issue by artifactdev** [alexa-js/alexa-app#160]
Please add a possibility to set a default value for a slot. So that there won't be an error like "Cannot read property 'value' of undefined" if a slot ist not filled.

**Comment by dblock** [comment]
Do you think you can write a test that demonstrates `Cannot read property 'value' of undefined"`?

**Comment by artifactdev** [comment]
If I've got time, yes. Shouldn't be a big thing to clone a test for slots / utterances and let one empty.

**Comment by ajcrites** [comment]
You can set default values for slots: https://github.com/alexa-js/alexa-app/blob/master/index.js#L176

**Comment by dblock** [comment]
Should we handle this better and produce an error such as no default value for slot?

**Comment by ajcrites** [comment]
You will already get an error if there is no value for the slot even if you provide a default value. Allowing provision of a default value is nice, but I think it's actually unnecessary since you can really just do:

    req.slot("SlotName") || defaultValue;

If the slot is a deeply nested object you can use a library to do this as well:

    lodash.get(req.slot("SlotName"), "some.deeply.nested.value", defaultValue);
