### ISSUE TITLE
express.post is not a function

### ISSUE THREAD

**Issue by tombarton** [alexa-js/alexa-app#161]
Hi there,

Apologies for the lack of detail around this, but I'm struggling somewhat.

I've used the example code for an express integration, but the application fails as soon as I start it with the following error:

```
TypeError: express.post is not a function
    at express (/home/ubuntu/workspace/node_modules/alexa-app/index.js:491:13)
    at Object.<anonymous> (/home/ubuntu/workspace/server.js:10:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

I have removed all dependencies from my `package.json` and any other files, but I'm still getting the error. However, when I use the code in a fresh project, it is working as expected.

**Comment by tombarton** [comment]
As expected, this was a local environment issue. Sorry!

**Comment by alistairpaul** [comment]
@tombarton Tom, any chance you can help me out with what was causing this?  Between yesterday and today I have found myself in this same situation and am trying to eliminate variables of what it might be.

**Comment by tombarton** [comment]
@alistairpaul I'd suggest removing your `package.json` and starting with just `alexa-app`. Start adding dependencies back in one at a time until you find the troublemaker.

**Comment by xunxdd** [comment]
i have the same issue. trying with only sample apps provided. hello-world does not even start. package.json has only alexa-app

**Comment by xunxdd** [comment]
uninstall/rm the alexa-app module inside the hello-world app would rid of this problem

**Comment by andermoran** [comment]
Could someone give any details on how they solved this? The comments above didn't help me

**Comment by maurermax** [comment]
For me the issue was that I used an older version on how to pass the express object

```
    alexaApp.express({ expressApp: app }); //outdated
```
The above is **outdated**.

Instead I am now using 

```
    alexaApp.express(app); //works
```
