### ISSUE TITLE
Unable to call any response commands inside a Promise .then

### ISSUE THREAD

**Issue by kenibarwick** [alexa-js/alexa-app#164]
Hi, I'm a little new to Node so please be gentle. 

What am I doing wrong below... I'm just simply request Alexa to say the result of a request-promise. 

Your thoughts and advice greatly appreciated.

```
var rp = require('request-promise');
var ENDPOINT = 'http://httpd.apache.org/server-status?view=json'

app.launch(function(req,res) {
	
	var options = {
		uri: ENDPOINT,
		transform: function (body, res, resolveWithFullResponse) {
			return JSON.parse(body);
		}
	};
	
	rp(options)
		.then(function (bodyObj) 
		{
			res.say(bodyObj.server.host);
		});
});
```

**Comment by dblock** [comment]
You have to return the promise as well, try with `return rp. ...`?

**Comment by kenibarwick** [comment]
Unfortunatly that's not it.... I added a .send() and also returned the promise like below.

`	rp(options)
		.then(function (bodyObj) 
		{
			res.say(bodyObj.server.host).send();
			return rp;
		});
`

**Comment by dblock** [comment]
You have to return the promise from the function itself, like this:

```
return rp(options).then(function (bodyObj) { 
  res.say(bodyObj.server.host).send(); 
});
```

Put up some code on Github if you can't figure it out.

**Comment by kenibarwick** [comment]
Thanks for that... I've added the return on the rp to no avail... As per your suggestion I've added a Github repository for you to have a look at.

https://github.com/kenibarwick/helloKeni

I appreciate your time

**Comment by dblock** [comment]
The code was correct, but you were using an older version of alexa-app (2.1.0) that doesn't support promises. Fix with a working express example in https://github.com/kenibarwick/helloKeni/pull/1.

**Comment by kenibarwick** [comment]
Thanks for you help, that indeed did fix it
