### ISSUE TITLE
AudioPlayer.PlaybackFinished can't respond with play directives

### ISSUE THREAD

**Issue by wschaeferiii** [alexa-js/alexa-app#169]
Not an issue with the library, rather the readme.

`AudioPlayer.PlaybackFinished` can't respond with play directives, only stop and clear queue directives, per [documentation](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/custom-audioplayer-interface-reference#playbackfinished).

On a `app.audioPlayer(PlaybackFinished...` event, which gives throws the error 'Can't respond with more than 0 play directives'.  You'd need to use `app.audioPlayer(PlaybackNearlyFinished...`

**Comment by dblock** [comment]
Would you be so kind to PR a fix? Thanks.

**Comment by wschaeferiii** [comment]
Will do.  Prob this weekend.

**Comment by kobim** [comment]
Resolved via #379
