### ISSUE TITLE
Release 3.1.0 with deprecation of non-promise version

### ISSUE THREAD

**Issue by dblock** [alexa-js/alexa-app#173]
See https://github.com/alexa-js/alexa-app/pull/167.

@ajcrites Want to cut a release, maybe not 3.0.1 but 3.1.0 that includes #167? We have https://github.com/alexa-js/alexa-app/blob/master/RELEASING.md with instructions.

What's your npm email? I'll add you.

**Comment by ajcrites** [comment]
@dblock npm email is ajcrites@gmail.com -- I'll work on this.

**Comment by dblock** [comment]
Added you to npm @ajcrites. Go for it.

**Comment by ajcrites** [comment]
This is done: https://www.npmjs.com/package/alexa-app
