### ISSUE TITLE
Rewrite for ES6

### ISSUE THREAD

**Issue by ajcrites** [alexa-js/alexa-app#175]
I would be very interested in rewriting the source for ES6/7/2015/16/17/18 and updating prepublish to transpile. I would create a `src/index.js` that would transpile using babel to a target of `lib/index.js` which would be `main` for package.json.

This should not change any functionality at all and would really just be an exercise and hopefully provide a good example repo for ES6+ practices.

I'd be interested to hear reasons not to do this as well.

**Comment by dblock** [comment]
There was a discussion about TypeScript in https://github.com/alexa-js/alexa-app/issues/148. 

This code runs server-side on node, so how would this be useful?

**Comment by ajcrites** [comment]
I'm not sure I understand what you mean by this running server side having an impact on changing how the source was written from being useful.

Updating the source is probably not particularly useful, but there are some ES6 features we could take advantage of to make the code cleaner -- particularly arrow functions. This is really just my opinion, though.

I can understand the desire not to have an additional transpilation step which we would need if we want to support down to 0.12.

I'm going to go ahead and close this since if we don't want to move ahead with TS we probably wouldn't move ahead with ES6 either.

**Comment by dblock** [comment]
Right. Usually I think there's a lot of advantage of using TS for projects that need to run on many browsers. But for node projects it's less relevant as the matrix is not that crazy.

**Comment by tejashah88** [comment]
> there are some ES6 features we could take advantage of to make the code cleaner -- particularly arrow functions

While I do agree upon this statement, it's worth noting that there are very minor side effects. For example, using arrow functions in mocha tests is discouraged (source: https://mochajs.org/#arrow-functions).
