### ISSUE TITLE
Switch to `callback` for lambda instead of the `context` object

### ISSUE THREAD

**Issue by ajcrites** [alexa-js/alexa-app#188]
Since node v4.3 on Lambda, using the [`callback`](http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-handler.html#nodejs-prog-model-handler-callback) parameter is preferred to indicate lambda function completion rather than using `context.succeed` or `context.fail`.

I would like to make this change. This would be a potentially breaking change that we can include in v4. The big difference is that the `context` methods don't wait for an empty event loop so any lambda functions relying on that functionality would be broken.

**Comment by dblock** [comment]
I can't claim I understand what this is, but if it's the preferred method go for it.
