### ISSUE TITLE
helpIntent & stopIntent

### ISSUE THREAD

**Issue by artifactdev** [alexa-js/alexa-app#192]
How can this standard Intents be handled? My skill missed certification because this two are missing.

**Comment by dblock** [comment]
You can implement them in a straightforward way. I have a certified skill in https://github.com/artsy/elderfield that could be a good example with things like:

```js
app.intent('AMAZON.HelpIntent', {
    "slots": {},
    "utterances": [
      "help"
    ]
  },
  function(req, res) {
    console.log('app.AMAZON.HelpIntent');
    res.say("Artsy’s mission is to make all the world’s art accessible to anyone with an Internet connection. You can ask Artsy about an artist. For example say ask Artsy about Norman Rockwell. What artist would you like to hear about?");
    res.shouldEndSession(false);
    res.send();
  }
);
```

You might also want to read http://artsy.github.io/blog/2016/11/30/bringing-artsy-to-amazon-echo-alexa/
