### ISSUE TITLE
Updating code to Promises to comply with 4.0

### ISSUE THREAD

**Issue by QuentinDela** [alexa-js/alexa-app#194]
Hello, 

I am a bit new to Promises and I am struggling to update my code for the future version of alexa-app. Here is an intent I would like to update for example. I am currently use alexa-app 3.2.0. Could you share your input to help me on this? Thanks a lot!

```
app.launch(function(request, response) {
	var accessTokenReceived = request.sessionDetails.accessToken;
	async.waterfall([
		// STEP 1: check the accessToken
		function(callback) {
			if (accessTokenReceived === undefined) {
				callback('no_access_token');
			}else{
				user.getUserFromAccessTokenPromise(accessTokenReceived).then(function(user) {
					callback(null,user);
				}, function(err){
					var obj = {};
					callback("not_good_access_token");
				});
			}
		},
		//STEP 2 : check stuff
		function(user,  callback) {
			stuff.getStuffFromUserPromise(user).then(function(stuff){
				callback(null, stuff, user, userId);
			},function(err){
				callback("no_stuff");
			});
		},
		function(stuff, user, userId, callback) {
			helper.getStaffUserIdPromise(userId).then(function(staff){
				if (numberOfStaff !== 0) {
					response.say(config.dialog.onLaunchIntent.case13.say);
					response.reprompt(config.dialog.onLaunchIntent.case13.reprompt);
					response.card(config.dialog.onLaunchIntent.case13.cardTitle, config.dialog.onLaunchIntent.case12.card);
					response.shouldEndSession(config.dialog.onLaunchIntent.case13.end);
					response.send();
					callback(null, stuff, user, userId, staff);
				} else {
					callback("no_staff");
				}
			}, function(err){
				callback("error_retrieving_staff");
			});
		},
	], function (err, stuff, user, userId, staff) {
		if(err){
			switch (err) {
				case "no_access_token":
				response.say(config.dialog.onLaunchIntent.case10.say);
				response.reprompt(config.dialog.onLaunchIntent.case10.reprompt);
				response.linkAccount();
				response.shouldEndSession(config.dialog.onLaunchIntent.end);
				response.send();
				break;
				case "not_good_access_token":
				response.say(config.dialog.onLaunchIntent.case10.say);
				response.reprompt(config.dialog.onLaunchIntent.case10.reprompt);
				response.linkAccount();
				response.shouldEndSession(config.dialog.onLaunchIntent.case10.end);
				response.send();
				break;
				case "no_stuff":
				response.say(config.dialog.onLaunchIntent.case11.say);
				response.reprompt(config.dialog.onLaunchIntent.case11.reprompt);
				response.card(config.dialog.onLaunchIntent.case11.cardTitle, config.dialog.onLaunchIntent.case11.card);
				response.shouldEndSession(config.dialog.onLaunchIntent.case11.end);
				response.send();
				break;
				case "no_staff":
				response.say(config.dialog.onLaunchIntent.case12.say);
				response.reprompt(config.dialog.onLaunchIntent.case12.reprompt);
				response.card(config.dialog.onLaunchIntent.case12.cardTitle, config.dialog.onLaunchIntent.case12.card);
				response.shouldEndSession(config.dialog.onLaunchIntent.case12.end);
				response.send();
				break;
				default:
				response.say(config.dialog.onLaunchIntent.case6.say);
				response.reprompt(config.dialog.onLaunchIntent.case6.reprompt);
				response.card(config.dialog.onLaunchIntent.case6.cardTitle, config.dialog.onLaunchIntent.case6.card);
				response.shouldEndSession(config.dialog.onLaunchIntent.case6.end);
				response.send();
			}
		}
	});
	return false;
});
```

**Comment by dblock** [comment]
Do you have the project up? With tests?

**Comment by QuentinDela** [comment]
Hey Daniel, 

I can share the project with you. 

Here is what I ended up doing. I don't if it the cleanest way to do. 

`app.launch((request, response) => {
	return launchIntent(request).then((dialog) => {
		response.say(dialog.say)
		response.reprompt(dialog.reprompt)
		response.card(dialog.cardTitle, dialog.card);
		response.shouldEndSession(dialog.end);
		response.send();
	}).catch((error) => {
		console.log("error", error)
	})
})


var launchIntent = (request) => {
	return new Promise((resolve,reject) => {
		var accessTokenReceived = request.sessionDetails.accessToken;		
		if (accessTokenReceived === null) {
			resolve(config.dialog.onLaunchIntent.case13)
		} else {
			return user.getUserFromAccessTokenPromise(accessTokenReceived).then(function(user) {
				if (!user) {
					resolve(config.dialog.onLaunchIntent.case10.xp1.var1)
				} else {
					var userId = user.id;
					return contactList.getStuffFromUserIdPromise(userId).then(function(Stuff){
						if (!Stuff){
							resolve(config.dialog.onLaunchIntent.case11.xp.var1)
						} else {
							return helper.getStaffFromUserIdPromise(userId).then(function(Staff){
								if (Staff === 0){
									resolve(config.dialog.onLaunchIntent.case12)
								} else {
									resolve(config.dialog.onLaunchIntent.case13)
								}
							})
						}
					})
				}
			})
		}
	})
}`

**Comment by ajcrites** [comment]
I think that you may want to stick with using 3.2 as updating your current style will be quite a bit of refactoring. There are some issues in your code (probably just a result of copy/pasting) so this won't work out of the box, but it is a close analog. The point of promises is to try to keep things to a single chain.

Ideally you would only need one `catch` and you could derive the actual error from the caught value, i.e. the error you get from `getUserFromAccessTokenPromise` or `getStuffFromUserPromise` would be different and you could look at that value in the error in the final catch rather than catching each individual error returned by that promise and then throwing a separate error. If these errors exist throughout your app, consider using `app.error` to handle them as well as it is also part of the app's promise chain.

Note that using `response.send()` is not needed since it gets called automatically when the promise chain resolves.

Example that should work with your existing code: https://gist.github.com/ajcrites/3dbb77998f33ef9f0700bd4f5f748b07

Ideal example (your promise functions throw corresponding error messages): https://gist.github.com/ajcrites/323dc219b588ca7f76c24afe95d03078

**Comment by ajcrites** [comment]
@QuentinDela if this helps can we close this issue? Would you recommend any more updates to the documentation to make this clearer?

**Comment by QuentinDela** [comment]
Hey @ajcrites

Thanks a lot for your help, your answer was awesome. 
If anyone is using your template, there is a token to remove at the end of the first line. 
I also had to change throw new Error("no_staff"); to throw "no_staff";

You are doing an awesome job with alexa-app. 
Do you know what would be the way to build tests for alexa-app intents?

**Comment by dblock** [comment]
I have a bunch of tests in https://github.com/artsy/elderfield, and some explanation in http://artsy.github.io/blog/2016/11/30/bringing-artsy-to-amazon-echo-alexa/.

Most of our tests look like this:

```js
chai = require('chai');
expect = chai.expect;
chai.use(require('chai-string'));
chai.use(require('chai-http'));

var server = require('../server');

describe('artsy alexa', function() {
    it('tells me about Norman Rockwell', function(done) {
        var aboutIntentRequest = require('./AboutIntentRequest.json');
        chai.request(server)
            .post('/alexa/artsy')
            .send(aboutIntentRequest)
            .end(function(err, res) {
                expect(res.status).to.equal(200);
                var data = JSON.parse(res.text);
                expect(data.response.outputSpeech.type).to.equal('SSML')
                var ssml = data.response.outputSpeech.ssml;
              expect(ssml).to.startWith('<speak>American artist Norman Rockwell ');
              done();
            });
    });
});
```
