### ISSUE TITLE
How to get a question answer style conversation?

### ISSUE THREAD

**Issue by airsidemap** [alexa-js/alexa-app#196]
This might be something obvious but I cannot figure it out, how can I answer to questions I ask in a intent?
For Example:
`res.say(‘do you want me to go on?’).reprompt(Please anwser "Yes" or "No").shouldEndSession(false)`
`// if( Answer == true){`
`// res.say(‘something …’)`
`//}`
`//else{`
`// res.say(‘goodby’)`
`//}`

I know other intents can be called form this point but how do I stay in my intent and get the answer?

**Comment by dblock** [comment]
I think you keep track of the current state/intent in a session and implement yes/no intent. [This tutorial](https://developer.amazon.com/blogs/post/TxHGKH09BL2VA1/new-alexa-skills-kit-template-step-by-step-guide-to-build-a-decision-tree-skill) seems to imply that, it supports multiple questions.

**Comment by ericblade** [comment]
Yes, you need to respond to each question individually, and you may keep track of where you are either locally or via session data back-and-forth.

Official alexa-sdk has an 'ask' event that handles the most basic parts of that (outputting a voice question, and setting the session to not close), which i'm intending on making a pull request to add here, if i get time this weekend, and anyone would be interested.  It's just a shorthand.
