### ISSUE TITLE
interrupt while response.say

### ISSUE THREAD

**Issue by pYr0x** [alexa-js/alexa-app#201]
i have a long text returning to alexa.
but i cant interrupt that response by saying "STOP" or something else.
i have a `AMAZON.StopIntent` but this i not called.
do i miss something?

**Comment by dblock** [comment]
I think this is a limitation of the platform, you can however say `Alexa, stop`, no?

**Comment by pYr0x** [comment]
`Alexa, stop` will have no result.
but with the `Brieding Skill` you can interrupt alexa while alexa is reading some news. how that work?

**Comment by jlguinn** [comment]
In my experience not only can you say "Alexa stop" but you can interrupt with whatever your next desired intent.

In my adventure game, I often do this when testing something. I don't need to hear the entire narrative so I'll just interrupt with "Alexa, go left." or "Alexa, check my inventory" even before she is done speaking.  If you wait until Alexa is done speaking in an open session then you no longer have to interrupt with the wake word.

**Comment by ajcrites** [comment]
The wake word should interrupt Alexa before she is done speaking as @jlguinn says. This is not something we can control with this library, but it should be working fine.

**Comment by ericblade** [comment]
pyr0x not aware of any way to get a normal Echo device to listen to anything other than the wake word while outputting .. . . . can you link to this skill that you say is an example?
