### ISSUE TITLE
Can't save because of Tab (whitespace) in sample utterances

### ISSUE THREAD

**Issue by McGern** [alexa-js/alexa-app#203]
Hi,

Great tool, thanks!

Don't know if this is a new thing with the Alexa Skill Kit (coz it didn't seem to be an issue last week), but when trying to import the sample utterances generated by the tool it won't save and gives the message "Error: There was a failure saving the intent schema or sample utterances, please try again." (super helpful error message from Amazon).

I pasted into notepad++ and removed all of the tabs and then it saved. Don't know if this is related to issue #18 

Cheers,
Jarrod

**Comment by jmihalicza** [comment]
I have a possible fix for that here: https://github.com/jmihalicza/alexa-app/commit/7e88091f841f4ebbaaef557f784f4badf1abcbcf
I could not test it, so did not create a PR.

**Comment by dblock** [comment]
Closed via https://github.com/alexa-js/alexa-app/pull/204.
