### ISSUE TITLE
Strangeness with mute echo 

### ISSUE THREAD

**Issue by mdelete** [alexa-js/alexa-app#206]
Both examples will yield the same result if you type it in the Service Simulator, but in the _first_ example my echo device won't speak. Why is that?

Example with 5ms waiting async function, echo does not speak:

```
myApp.intent("HelloWorldIntent", {
		"utterances": [ "say hello world" ]
    },
    function(request, response) {
    
    	console.time("exectime");

    	setTimeout(function() {
    		response.say('Hello World.').shouldEndSession(true);
    		console.timeEnd("exectime");
	}, 5);

    }
);
```

Example with 5ms bad busy waiting works:

```
myApp.intent("HelloWorldIntent", {
		"utterances": [ "say hello world" ]
    },
    function(request, response) {
    
    	console.time("exectime");
		
	/* busy waiting 5ms */
	var wait = new Date(new Date().getTime() + 5);
	while(wait > new Date()){}
    	
    	response.say('Hello World.').shouldEndSession(true);
    	
    	console.timeEnd("exectime");
    }
);
```

**Comment by dblock** [comment]
If you're using 4.0.0 you need to return a promise or `false` in older versions, otherwise the session will be closed before you get a chance to hit `say`. Maybe [this SO](http://stackoverflow.com/questions/22707475/how-to-make-a-promise-from-settimeout) is a good place to start.

**Comment by mdelete** [comment]
Ah, thanks, trap for young players. The response got to the Service Simulator and cards correctly though, just the Echo was mute. This could lead to some confusion.

**Comment by dblock** [comment]
If you think the doc can be clearer, please contribute by all means! It's a common problem.
