### ISSUE TITLE
Async Request Not Receiving Response 

### ISSUE THREAD

**Issue by Archetype90** [alexa-js/alexa-app#207]
I have a fairly simple intent, which is supposed to publish something to an MQTT topic using AWS-SDK. I am currently using alexa-app v4.0.0. 

```
app.intent('DeviceNumber', {
    'utterances': [
      'number of devices',
      'the number of the devices',
    ]
  },
  function(req, res) {
    var iotdata = new awsIot.IotData(config.iotDevice);

    var params = {
      topic: 'DeviceNumber',
      payload: 'blah',
      qos: 0
    };
		
    return iotdata.publish(params, function(err, data) {
      if (err) {
        res.fail();
        console.log(err);
      } else {
        console.log("success!");
        return res.send("Request sent...");
      }
    })
  }
);
```

After deploying this to Lambda, and testing with the following... 

```
{
  "session": {
    "new": false,
    "sessionId": "amzn1.echo-api.session.xxxxx",
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account.xxxxx"
    },
    "application": {
      "applicationId": "amzn1.ask.skill.xxxxx"
    }
  },
  "version": "1.0",
  "request": {
    "locale": "xxxxx",
    "timestamp": "xxxxx",
    "type": "IntentRequest",
    "requestId": "amzn1.echo-api.request.xxxxx",
    "intent": {
      "name": "DeviceNumber"
    }
  }
}
```

The intent successfully logs "success" to console andpublishes the "blah" message to the DeviceNumber topic, but the response from AWS is - 

```
{
  "version": "1.0",
  "response": {
    "directives": [],
    "shouldEndSession": true
  },
  "sessionAttributes": {}
}
```

I have followed the documentation - looking at both upgrading and the standard doucmentation and tried a few variations of returning a response (res.say("x"), return res.send, etc). I should note that if I remove all of the async stuff and just tell it to res.say() when I receive that intent, it works just fine. So I am clearly not understanding something with the "promise chain" and async calls. 

Could anyone help point out where my issue is? Thanks!

**Comment by Archetype90** [comment]
A quick note - I am able to get around this problem by doing res.say("blah") before attempting to publish to the topic. But I was really hoping to only have it say something like "Request received" after it knows it was successfully published to the topic.

**Comment by dblock** [comment]
You have to return an actual Promise to do an async call, it doesn't look like `iotdata.publish` does, https://www.promisejs.org/ is probably a good place to start. Let us know what you come up with and if you can't make it work?

**Comment by Archetype90** [comment]
@dblock Thank you for the response. I have successfully implemented the code as a promise, but I still am not able to get the response. I will include some documentation here in case the problem comes up for someone else:

The AWS SDK does support promises, and the promise handler must be set. Information on this can be found here:

https://aws.amazon.com/blogs/developer/support-for-promises-in-the-sdk/

I have updated my code based on the above link and the Alexa-App documentation, but as I mentioned, I am still not receiving the response. Here is the updated code:

```
app.intent('DeviceNumber', {
    'utterances': [
      'number of devices',
      'the number of the devices',
    ]
  },
  function(req, res) {
    var iotdata = new awsIot.IotData(config.iotDevice);

    var params = {
      topic: 'DeviceNumber',
      payload: 'From DeviceNumber intent!',
      qos: 0
    };

    return iotdata.publish(params).promise().then(function(data) {
	console.log('Success');
	return res.send('Request sent...');
    }).catch(function() {
	console.log('Error');
    });
  }
);
```

The behavior is the same in Lambda - as seen in my results (of the same test) below:

```
{
  "version": "1.0",
  "response": {
    "directives": [],
    "shouldEndSession": true
  },
  "sessionAttributes": {}
} 
```

Hopefully I have some silly mistake that you can point out?

**Comment by dblock** [comment]
I don't see anything wrong, can you put this project on Github with a very easy way to reproduce this? I can take a look.
