### ISSUE TITLE
Http-Request issue with request promise module

### ISSUE THREAD

**Issue by niho1** [alexa-js/alexa-app#210]
Hi there, 
I'm new to alexa-app and even node.js however everything is going straight forward with this module except one thing: Im going to a tutorial from big nerd ranch using this source code: https://github.com/bignerdranch/alexa-airportinfo/blob/master/index.js

the code-part which does not work is this here: 
`faaHelper.requestAirportStatus(airportCode).then(function(airportStatus) {`
      ` console.log(airportStatus);`
        `res.say(faaHelper.formatAirportStatus(airportStatus)).send();`
      `}).catch(function(err) {`
        `console.log(err.statusCode);`
        `var prompt = 'I didn\'t have data for an airport code of ' + airportCode;`
         //https://github.com/matt-kruse/alexa-app/blob/master/index.js#L171
        `res.say(prompt).reprompt(reprompt).shouldEndSession(false).send();`
      `});`

the request is working well but the  execution of "res.say(.....).send()" is somehow not working properly. when you run it in a local testserver (alexa-app-server) nothing is responded in this case. 
So it seems to be that res.say().send() is empty at the point when it is triggered. 
Can someone help?
Regards Nils

**Comment by ajcrites** [comment]
As of v4, `response.send()` returns the promise chain for pre/intent/post handling. You need to return it to any promise used, and this means you also need to return it to the intent handler:

    app.intent("FAAIntent", (req, res) => {
      return faaHelper.requestAirportStatus(airportCode).then(airportStatus) => {
        return res.say(faaHelper.formatAirportStatus(airportStatus)).send();
      });
    });

**Comment by dblock** [comment]
@mutexkid you might want to update that tutorial ^
