### ISSUE TITLE
Add a break (pause) between each say

### ISSUE THREAD

**Issue by manikawnth** [alexa-js/alexa-app#211]
Between each say of response add a break as per SSML.
I think this can be achieved today by making it part of the SSML string of `response.say(SSML)` but the following functions are more intuitive.

```
response.say(text).addBreak(breakType) //or
response.say(text).addBreak(breakTime)

/*
breakType has the following values:
'c' => represents command and maps to <break strength='medium'>
's' => represents command and maps to <break strength='strong'>
'p' => represents command and maps to <break strength='x-strong'>

breakTime can be forced to have the values in milliseconds
number => max of 10000 and maps to SSML <break time='5000ms'>
*/
```

Or, we can have more human understandable functions like

```
response.commaBreak()
response.sentenceBreak()
response.paraBreak()
response.timeBreak(time)
```

**Comment by ajcrites** [comment]
This is actually built in functionality for https://github.com/TheFuzzy/node-ssml so you can use that library to build your ssml strings for `response.say`.  I wouldn't want to overload this functionality.
