### ISSUE TITLE
Newbie help "Getting Started with Server"

### ISSUE THREAD

**Issue by scottfree1** [alexa-js/alexa-app#212]
I'm lost here, am I cloning this to Aws or to a local node.js server? And if it is local I've installed node.js in windows but can these cmds be run in a node.js cmd window or should they be run in linux terminal or linux node'js? Thanks, my first attempt with all this, sure is a big learning curve just to add voice to my thermostat.

###Getting Started with Server

Clone the app git clone https://github.com/bbrookfield/node-alexa-server
Install modules npm install
Run the application PORT=9000 node app.js
If no errors occur then you can begin adding modules or create your own module

**Comment by ericblade** [comment]
Heh.  Good luck :)

You might be better off asking questions over on that server's github page.  Looks like that person's code uses alexa-app, for it's skills, though?

I can't say specifically that that particular server works in Windows, but most likely, that'll work fine in Windows, almost all node code does.

But in Windows, you can't put the PORT=9000 line on that command like that.
You'd have to do something like

````
c:\wherever\node-alexa-server> set PORT=9000
c:\wherever\node-alexa-server> node app.js
````

I can say that the alexa-app-server here works fine in Windows.

**Comment by jlguinn** [comment]
I'm not familiar with the link you're posted but for beginner level info on how to use this alexa-app-server look at https://www.bignerdranch.com/blog/developing-alexa-skills-locally-with-nodejs-setting-up-your-local-environment/ (first in a six part blog tut). In part 2, they cite the original Matt Kruse repository that I believe this repository was forked from (I'm enough of a noob to not be certain on my terminology, but I'm pretty confident that will get you started using this codebase). Apologies if I misrepresented anything. Just trying to help.

**Comment by dblock** [comment]
I had posted a video on getting started with your first alexa skill, maybe that can help.
http://code.dblock.org/2017/02/16/building-a-simple-alexa-skill-live-code.html

I'll close this. Feel free to ask specific questions.
