### ISSUE TITLE
User in Session Object Syntax

### ISSUE THREAD

**Issue by danielstieber** [alexa-js/alexa-app#214]
Hey, I just started with alexa development, so I hope this is a real issue, but I think the session object is using a different Syntax for the **User Data.**

Session Object of my Skill using alexa-app

```
{ isAvailable: [Function],
  isNew: [Function],
  get: [Function],
  set: [Function],
  clear: [Function],
  details:
   { new: true,
     sessionId: 'amzn1.echo-api.session.abeee1a7-aee0-41e6-8192-e6faaed9f5ef',
     userId: 'amzn1.account.XXXXXXXXXXXXXXXXXXX',
     accessToken: null,
     attributes: { },
     application: { applicationId: 'amzn1.echo-sdk-ams.app.XXXXXXXXXXX' } },
  attributes: { },
  sessionId: 'amzn1.echo-api.session.abeee1a7-aee0-41e6-8192-e6faaed9f5ef',
  getAttributes: [Function] }
```

If you look at the session.details (which I guess should be the same as the original Session JSON Object) it gives me **userId and accesToken.**

In original Object Syntax (https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-interface-reference#request-body-syntax) is me a **user Object** with the data in it:

```
{
    "new": true,
    "sessionId": "string",
    "application": {
      "applicationId": "string"
    },
    "attributes": {
      "string": {}
    },
    "user": {
      "userId": "string",
      "accessToken": "string"
    }
  }

```

Hope this helps!

All the best, Daniel

**Comment by dblock** [comment]
Are you saying the doc is incorrect? If so please PR a fix? thx

**Comment by danielstieber** [comment]
Actually I think the session object syntax in alexa-app is incorrect. Everywhere else it is like in the docs.

**Comment by dblock** [comment]
OK, you should PR a fix. Maybe nobody uses it and therefore there has never been an issue? Try to build this into an example too and actually test it.

**Comment by danielstieber** [comment]
Ok, I will do that now. Thanks!

**Comment by danielstieber** [comment]
Added the Request here: https://github.com/alexa-js/alexa-app/pull/215

**Comment by ericblade** [comment]
.. i'm confused. Is what it is returning contrary to the documentation? or does the documentation not say anything about the topic?  

What alexa-skills-kit does is not exactly relevant -- if I'm not mistaken, the return of getSession().details should be exactly the data as it was posted by AVS.

**Comment by danielstieber** [comment]
sorry for the confusion.

The getSession().details is different to the original session from the request. I think this is not what it supposed to be.

console.log(getSession().details);
`
{ new: true,
  sessionId: 'amzn1.echo-api.session.abeee1a7-aee0-41e6-8192-e6faaed9f5ef',
  userId: 'amzn1.account.XXXXXXXXXX',
  accessToken: null,
  attributes: {},
  application: { applicationId: 'amzn1.echo-sdk-ams.app.XXXXXXXXXX' } }
`

console.log(request.data.session);
`
{ new: true,
  sessionId: 'amzn1.echo-api.session.abeee1a7-aee0-41e6-8192-e6faaed9f5ef',
  application: { applicationId: 'amzn1.echo-sdk-ams.app.XXXXXXXXXX' },
  attributes: {},
  user: { userId: 'amzn1.account.XXXXXXXXXX' } }
`

**Comment by ericblade** [comment]
right.. so it would seem that the session management in alexa-app is flattening that out, a bit.  Is that how it's documented? or is it not documented at all.. ?  i'm looking at my local copy, and i don't see any documentation that indicates that it should or shouldn't be flattened like that.

**Comment by dblock** [comment]
Closed via https://github.com/alexa-js/alexa-app/pull/215.
