### ISSUE TITLE
is it possible to do asynchronous things in pre() ?

### ISSUE THREAD

**Issue by mreinstein** [alexa-js/alexa-app#22]
I want my `pre()` to able to make asynchronous calls before running the request. like this:

``` coffeescript
app.pre = (request, response, type) ->
  getAccessToken request.data.session.user.userId, (er, token) ->
    if er or (not token)
      response.fail 'Sorry, you must link your device first.'
    else
      # TODO: proceed to normal intent handler
```

Is there a way to do asynchronous things in pre?

**Comment by OverloadUT** [comment]
Sounds like pre() should use the same "return false" pattern that is present in the rest of the module (although personally I like the done() pattern used in Mocha :smile: )

**Comment by mreinstein** [comment]
> Sounds like pre() should use the same "return false" pattern that is present in the rest of the module 

That makes sense I think. The only trouble with that is introducing the change would break the existing API. We'd have to increment the major version number.

@matt-kruse is this change something you'd be open to? I can put together a PR if so.

**Comment by matt-kruse** [comment]
Returning false in intents requires the intent code to actually resolve the request and finish it. That won't work here, because there are still things to do after pre() is done.

I think that ideally pre() should return a Promise if it wants to be async. Then the rest of the processing could hook onto the return Promise. If pre() returns anything other than a Promise, it would be thrown away and consider sync, and execution would immediately continue.

Thoughts?

**Comment by mreinstein** [comment]
what if `pre` accepted a callback parameter as an optional 4th argument? Then it would be opt-in (if the callback arg isnt present or not a function assume its synchronous) and wouldn't break the existing API.

**Comment by OverloadUT** [comment]
Yeah, that's exactly what the tried and true Mocha pattern is. Super easy for the end developer, and backwards compatible too!

**Comment by ajagnanan** [comment]
Was this ever implemented?

**Comment by mreinstein** [comment]
if you don't see a PR then probably not. :)

I suspect this change won't ever be implemented because it doesn't fit the design patterns that alexa-app is based on.

**Comment by ajagnanan** [comment]
ok, i guess the alternative would be to call a common method from intents? guess that works too.

**Comment by OverloadUT** [comment]
Out of curiosity, how does it not fit the design patterns that alexa-app is based on? Seems to only make sense to me that the Intent methods and the pre() and error() methods should all have the same behavior when it comes to sync/async support.

Forcing the end-developer to call a common method from every single Intent method is pretty silly when that is the entire point of the pre() method

**Comment by jstreb** [comment]
Hoping to bump this thread. I am going to implement a common function that every single intent method is going to call, but it would be much more elegant if I could handle async functionality in pre. I personally like the tried and true suggestion of taking in an optional callback as a fourth parameter to the pre function. I am happy to push up PR for this but don't want to spend the time doing it if it will never be accepted. @matt-kruse thoughts?

**Comment by dblock** [comment]
Would take a pull request for this. I second that it should follow the existing `false` vs. `true` return pattern and not try to reintroduce some promise-based system _unless_ we change the skill implementation to the same. That's almost a separate feature request.

**Comment by ajcrites** [comment]
I also agree. I will implement this as part of my changes for #134
