### ISSUE TITLE
new card type available, AskForPermissionsConsent

### ISSUE THREAD

**Issue by ericblade** [alexa-js/alexa-app#223]
Per https://developer.amazon.com/blogs/alexa/post/75db99e4-dc77-42d1-89d1-aa8b41301324/build-more-engaging-skills-with-device-address-api-and-gain-insights-with-the-new-metrics-dashboard

Here's the specific documentation:

https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/device-address-api

**Comment by dblock** [comment]
Please contribute!

**Comment by ericblade** [comment]
Fixed in #225
