### ISSUE TITLE
post and session

### ISSUE THREAD

**Issue by kampfgnu** [alexa-js/alexa-app#224]
i want my skill to repeat the previous outputspeech, if the user asks for it.
so i decided to use post() to store whatever is contained in the response in the session attributes.
while implementing, i found that prepare() is called before calling post(), so all those session attributes are not stored in the response. therefore, i just call prepare() once again in my post() handler.
wouldn't it make sense to call prepare() after calling post() in the alexa-app?

cheers

**Comment by dblock** [comment]
I am not sure whether that's something we want to do all the time, but maybe you can convince us with a test that demonstrates this?

**Comment by ericblade** [comment]
I have to admit, I don't understand what kampfgnu is asking here.

**Comment by fremail** [comment]
Hi guys!

I just faced with a problem that I can't update session from post().

Example:

```var app = new alexa.app('TestApp');
app.pre = function (request, response, type) {
        var session = request.getSession();
        user = session.get('user');
        console.log('pre. session user: ', user);
});
...
app.post = function (request, response, type, exception) {
        var user = 11111;
        var session = request.getSession();
        session.set('user', user);
});
```
On every request I have `user = undefined` in `pre()`.

**Comment by fremail** [comment]
Calling `response.prepare();` at the end of app.post fixes the issue. But it's not clear for developers without looking at the alexa-app sources :D

**Comment by dblock** [comment]
Lets fix the code, PR please?

**Comment by fremail** [comment]
It's funny, but I faced with the bug again and it took me some time before I recall the issue.

@matt-kruse 
> The simple fix is moving response.prepare(); down after the post() call in response.send().

Actually not. `post()` is supposed to operate with prepared response, modify it.

We need to add `response.prepare();` after `post()` instead of moving it, IMHO.
