### ISSUE TITLE
How can I request session "new"

### ISSUE THREAD

**Issue by schaepersliam** [alexa-js/alexa-app#230]
Hello,
thanks that you taking your time for my issue.

I would like to request if the session is a new session or not(_true_ or _false_).

How can I do this with the **alexa-app** framework?

Thank you,
Liam

**Comment by dblock** [comment]
According [to the SDK docs](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-interface-reference#session-object) this is `session.new`, so I believe `request.getSession().new` should work.

**Comment by ericblade** [comment]
This seems to be the intended way?

````javascript
request.getSession().isNew()
````

**Comment by dblock** [comment]
Right, it compares with `=== true`, both should work though.

**Comment by schaepersliam** [comment]
Thanks for your fast help. 👍
