### ISSUE TITLE
Response Say to accept SSML

### ISSUE THREAD

**Issue by abrahaj** [alexa-js/alexa-app#237]
Considering SSML is being extended and the client might need to do more than just string to SSML, 
would it make sense to extend the SSML library to accept SSML code beside plain text? 
Or a way to send more than a Plain String to the Say function.
In my case I would benefit from the use of Pause functionality.

**Comment by dblock** [comment]
There're a number of libraries, notably https://github.com/nickclaw/alexa-ssml that do a lot more with SSML and are compatible with alexa-app, so you can `say` their output.
