### ISSUE TITLE
Release 4.0.1

### ISSUE THREAD

**Issue by danielstieber** [alexa-js/alexa-app#238]
@dblock, are there plans to release 4.0.1 soon?

Thanks again for all the work you put in here! 🙌

**Comment by dblock** [comment]
I can do it soon, but maybe @ajcrites or @tejashah88 have some cycles?

**Comment by dblock** [comment]
Thanks @ajcrites!

**Comment by tejashah88** [comment]
Technically this should have been a release 5.0.0, since we are dropping support for node v0.12 (#220). Granted, I'm not entirely sure how many people do use that version of node but we are introducing a breaking change in this case.

**Comment by dblock** [comment]
Indeed, but that ship has sailed.
