### ISSUE TITLE
not clear how to access user/accesstoken details

### ISSUE THREAD

**Issue by ericblade** [alexa-js/alexa-app#240]
Is there an intended method to access the userId or accessToken fields?

Right now, it's looking like

req.getSession().sessionDetails.userId and req.getSession().sessionDetails.accessToken

**Comment by ericblade** [comment]
looks like sessionDetails is not universally there, and i want req.getSession().details.accessToken  .. . . is that the intended method?

**Comment by dblock** [comment]
That seems like the right way AFAIK.
