### ISSUE TITLE
Can't run the basic example...

### ISSUE THREAD

**Issue by marcelolfilho** [alexa-js/alexa-app#242]
Hi.

Sorry for such a 101 question but I'm kinda new with Alexa and I'm facing a problem.

I had a Alexa skill working properly with NodeJS but I want to move to this approach once de configuration is in code and not on the cloud.

I'm trying to basically paste the example here https://github.com/alexa-js/alexa-app#aws-lambda and ask her to say me the number but I'm always facing the error:

> Sorry, the application didn't know what to do with that intent

What am I missing here?

Thanks.

**Comment by dblock** [comment]
@marcelolfilho Did you figure this out?

**Comment by marcelolfilho** [comment]
@dblock kind of, but i didnt have time to attack this again... I figured that I need serve the lambda as a HTTP service and not as a lambda itself right?

**Comment by dblock** [comment]
Not sure what that means. If you get back to it and get stuck on something specific we can try to help you! Closing this for now.
