### ISSUE TITLE
Echo show support

### ISSUE THREAD

**Issue by kevingilbert100** [alexa-js/alexa-app#243]
Will this support the echo show when the API becomes available and is there any insight on this?

**Comment by dblock** [comment]
If you contribute it, it will!

**Comment by kevingilbert100** [comment]
Sounds appropriate.

**Comment by ericblade** [comment]
My suspicion is that it will probably need to use the Directives support, as someone was working on here: https://github.com/alexa-js/alexa-app/pull/97

I don't have any specific information to that end, but directives have been enhanced recently to include beta conversational features (woe to us who just spent the last month working on the best ways to do that, only to have Amazon implement it for us :-D ), audio playback.. and directives are also the name of the commands sent to the Echo devices for how to "render" a request, be it playing audio, or synthesized speech .. so my guess is that to show something on a Show, you'll be sending a directive from the skill, and then AVS will send the directive to the rendering device to display images or video to it, as well as audio.

**Comment by kevingilbert100** [comment]
I'll be talking to Amazon soon about some of these questions around their new devices API support. Ill report back about it!

**Comment by kevingilbert100** [comment]
@ericblade You would be correct with that suspicion. https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/display-interface-reference#test-your-skill-with-a-visual-simulator

Should be pretty simple to wrap :) - Working on a solution over the next couple weeks.

**Comment by kevingilbert100** [comment]
Have started adding basic Display event support here https://github.com/kevingilbert100/alexa-app

**Comment by ArjunRajJain** [comment]
has this been added to the main package?

**Comment by kevingilbert100** [comment]
Grep the README for Display @ArjunRajJain

**Comment by dblock** [comment]
#263 was good, what else do we need to close this?

**Comment by dblock** [comment]
cc: @jstreb

**Comment by jstreb** [comment]
I am successfully using this library with an echo show skill. There are couple of gotchas to be aware of, such as making sure you don't return templates to non-show devices and handling special characters. But this library gives you everything you need to support it. If anyone has any questions, I am happy to help.

**Comment by dblock** [comment]
@jstreb Could you PR something into the README that speaks to what the library is compatible with and we can close this?

**Comment by jstreb** [comment]
Sure, will do so later this weekend.

**Comment by jstreb** [comment]
https://github.com/alexa-js/alexa-app/pull/292

**Comment by dblock** [comment]
Closed via https://github.com/alexa-js/alexa-app/pull/292.
