### ISSUE TITLE
Hybrid Alexa / Google

### ISSUE THREAD

**Issue by kevingilbert100** [alexa-js/alexa-app#244]
So I know each service has a very different API and very different possible use-cases. However that being said, I think it would be very cool to see a hybrid framework that could produce both a Google app and an Alexa app.

Thoughts?

**Comment by dblock** [comment]
I think it's a good idea and there're entire companies out there attempting to build generic things I believe (don't have one to recommend). Certainly this would be beyond the scope of this particular library, so I'll close this, but the library can be used to build a more generic framework.
