### ISSUE TITLE
New SSML Features (April 2017)

### ISSUE THREAD

**Issue by laurenceHR** [alexa-js/alexa-app#246]
Have you planing implement a way to use that new features?
https://developer.amazon.com/blogs/alexa/post/5c631c3c-0d35-483f-b226-83dd98def117/new-ssml-features-give-alexa-a-wider-range-of-natural-expression

**Comment by dblock** [comment]
Please contribute.

**Comment by laurenceHR** [comment]
Sure, is a deal! ;)

**Comment by tejashah88** [comment]
@laurenceHR I'd recommend looking at the [ssml-builder](https://github.com/mandnyc/ssml-builder) repo, which accounts for the [new features](https://github.com/mandnyc/ssml-builder#amazon-ssml-specific-tags).

**Comment by dblock** [comment]
Should we close this @tejashah88? Anything needs to be documented?

**Comment by tejashah88** [comment]
@dblock We can close it and just add a small section regarding constructing SSML responses.

**Comment by dblock** [comment]
Will you @tejashah88 ?

**Comment by tejashah88** [comment]
@dblock Yes, I'll look into submitting a PR soon.
