### ISSUE TITLE
Way to switch intents?

### ISSUE THREAD

**Issue by mwkrieger** [alexa-js/alexa-app#262]
Is there a way to trigger/switch an intent manually? 

My use case:
An intent is triggered. 
Logic is performed that decides if a user has access to this particular intent. 
If not, then pass the user to another intent on the alexa service and continue the interaction.

**Comment by dblock** [comment]
Not ATM, but this is a reasonable feature request, intents are really just functions, so we should have a documented way of calling another intent by name. Please contribute!

**Comment by maegnes** [comment]
Still interested in this feature? It's exactly what the "this.emitWithState('Intent');" from the official node.js sdk does (https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs#tips)

I will dive into the issue and hopefully send a pull requests the next days/weeks.

**Comment by lazerwalker** [comment]
Yeah, this still seems totally reasonable to me. I've ended up hand-rolling something like this in most Alexa skills I've built, seems logical to somehow expose the internal list of handlers by name.

**Comment by sof123** [comment]
Any progress on this?

**Comment by sof123** [comment]
@lazerwalker what did you do to accomplish this? can you show some example code?

**Comment by lazerwalker** [comment]
@sof123 I'm not exactly sure what sort of issues you're running into, but since handlers are just functions, you can just store a reference to them and call them as appropriate.

Here's a trivial example of what I was talking about:

```js
var intents = {};

intents.intentA = function(req, res) {
    res.say("Hello");
    return intents.intentB(req, res);
}

intents.intentB = function(req, res) {
    res.say("World");
}

app.intent("intentA", {
    "utterances": ["say 'hello world'"]
  },
 intents.intentA
});

app.intent("intentB", {
    "utterances": ["just say 'world'"]
  },
 intents.intentB
});

```
