### ISSUE TITLE
Support for Display.ElementSelected

### ISSUE THREAD

**Issue by jstreb** [alexa-js/alexa-app#263]
First of all thank you for your work on this project. I have really enjoyed developing skills using it and appreciate the continued updates.

We (http://www.rocketinsights.com) have begun working on a skill that is going to leverage the show. I can see that on the master branch there is some initial support for the directives, which is working out well for us. However, we do not see any support yet for the 'Display.ElementSelected' request type. We are happy to jump in and start adding support for this, but before doing so would love to know of any discussions that have already occurred or guidelines we should be aware of.

**Comment by jstreb** [comment]
We have added this functionality to our forked repo. Going to use this in our project and assuming it works well, will open a PR. In general we followed the existing patterns, specifically mimicking how library handles the launchRequest.

**Comment by jstreb** [comment]
Addressed in PR: #265

**Comment by dblock** [comment]
Closed via https://github.com/alexa-js/alexa-app/pull/265.
