### ISSUE TITLE
Release 4.1.0

### ISSUE THREAD

**Issue by djdiaz** [alexa-js/alexa-app#267]
I'm using this library for a project and I'd like to be able to use the dialog directive support being added for the 4.1.0 release. What remains to be done before the next version can be released? How stable is the current master branch?

**Comment by dblock** [comment]
Master is stable. I'll rename this issue to Release v.Next., any of the maintainers can do it (and usually feels free to do it).

**Comment by dblock** [comment]
@lazerwalker Want to do this one?

**Comment by lazerwalker** [comment]
@dblock Started on it, but I don't seem to have permissions to `npm publish`. Should I be getting that automatically as a maintainer of the repo, or does someone have to add @lazerwalker to the project on NPM?

**Comment by dblock** [comment]
@lazerwalker added lazerwalker to npm alexa-app

**Comment by lazerwalker** [comment]
Thanks @dblock!

@djdiaz 4.1.0 should be available on NPM! 🎉
