### ISSUE TITLE
Inconsistent definitions for request.slots

### ISSUE THREAD

**Issue by padraigkitterick** [alexa-js/alexa-app#272]
The documentation says that request.slots is a function, and that the slot object corresponding to 'SLOTNAME' can be returned as (https://github.com/alexa-js/alexa-app/commit/b4e110647d167f06d56269186298d2d66bdd7f8c#diff-04c6e90faac2675aa89e2176d2eec7d8R162):

`var slot = request.slots('SLOTNAME');`

This is compatible with the type definition for request, which defines slots as a function:

https://github.com/alexa-js/alexa-app/blob/13923cd1bf67824ecf6a779be36f07962df7e1d0/types/index.d.ts#L116

However, the implementation defines slots as an object with properties named after each slot:

https://github.com/alexa-js/alexa-app/blob/13923cd1bf67824ecf6a779be36f07962df7e1d0/index.js#L202-L209

This inconsistency was introduced in  https://github.com/alexa-js/alexa-app/commit/b4e110647d167f06d56269186298d2d66bdd7f8c.

**Comment by dblock** [comment]
Please PR a fix either way, thanks!

**Comment by lazerwalker** [comment]
Corresponding PR's been merged (thanks @padraigkitterick!), so going to close this.
