### ISSUE TITLE
Release 4.2.0

### ISSUE THREAD

**Issue by lazerwalker** [alexa-js/alexa-app#277]
A bunch of new stuff has gone in, we should release a new version once the few pieces of in-flight work are done:

- [x] https://github.com/alexa-js/alexa-app/pull/276
- [x] The questions in https://github.com/alexa-js/alexa-app/pull/271 (end-to-end testing, and what the type definitions should be for `getSession()`)
- [x] Any more type definition discrepancies that shake out as a result of aforementioned new tests

I'll cut the release, really just leaving this as a note for myself.

**Comment by lazerwalker** [comment]
Done!

**Comment by dblock** [comment]
Thans @lazerwalker !
