### ISSUE TITLE
Async Return on intent failing

### ISSUE THREAD

**Issue by cpup22** [alexa-js/alexa-app#281]
I need to call an async method on launch to do some account linking/checking but for some reason the promise .then method is never called so my skill times out.

```
app.launch(function(req, res) {
  return basicpromise(req, res).then(function(message){
       //this code NEVER called
        console.log("*********all done with linking... ");
        res.say(message).send();
        res.shouldEndSession(false);
    }, function(error){
        //this code NEVER called
        console.log("*******PROMISES FAILED: " + error);
        res.say("There was a problem with the promise!!!").send();
        res.linkAccount();
    }); //return a promise since it's an async task
});

function basicpromise(req, res){
    return new Promise(function(resolve, reject){
       //I see this log in my output.
        console.log("*******calling promise in linkOauthAccount test");
        resolve({"message":"Promise worked"});
    });
};
```

There are no errors in my console. And as you can see from my comments above neither the success or failure promise handler is invoked.  My skill worked fine before upgrading to the version that required the return of an async promise. So just converting everything to use the latest. Help appreciated.

**Comment by cpup22** [comment]
Oh, and tested my functions in jsbin to see if I was going crazy but this bin works just fine. calls the .then methods as I'd expect. 

`https://jsbin.com/norajudequ/1/edit?js,console`

**Comment by lazerwalker** [comment]
Are you using native ES6 promises or an alternate Promise library like Bluebird?

I've seen issues like that when using Bluebird, but switching to native promises fixed them. (Which might also explain why it works in JSBin?)

**Comment by cpup22** [comment]
@lazerwalker my code is right above. Super simple. Mind copying and pasting into an app to try it out yourself?  You can also try this snippet: https://pastebin.com/bRmkmSCZ.  I've tried about 8 different ways of doing promises to see if it were something wrong with my code but none of them triggered the "then".  @mreinstein even helped me debug a bit.

**Comment by dblock** [comment]
The inside of that `then` is not a promise, it's just a function. You also need to return a promise from within that, no?

**Comment by dblock** [comment]
@cpup22 (scratch what I said before) put up a simple repro that we can run?

**Comment by cpup22** [comment]
@dblock try this: https://github.com/cpup22/alexa-app-promisetest

**Comment by lazerwalker** [comment]
I just got this set up (cloned the repo, used `ngrok` to make my local server publicly-accessible, set up a new Skill on the Amazon dev portal pointed at that URL, put in a dummy interaction model, and then used the Amazon service simulator to fire off a LaunchRequest), and it worked 100% as expected:

CLI output:
```
stub A
*******calling promise in promisetest
stub B: Promise worked
```

JSON payload returned by the server:
```json
{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "ssml": "<speak>Promise worked OK</speak>",
      "type": "SSML"
    },
    "speechletResponse": {
      "outputSpeech": {
        "ssml": "<speak>Promise worked OK</speak>"
      },
      "directives": [],
      "shouldEndSession": false
    }
  },
  "sessionAttributes": {}
}
```

What version of node are you running? I was using v8.1.4.

**Comment by cpup22** [comment]
@lazerwalker I'm on node v8.4.0, npm 5.3.0 deployed to zeit now...

**Comment by dblock** [comment]
I would double check twice which version of alexa-app you're getting @cpup22?

**Comment by cpup22** [comment]
@dblock I'm on the latest `"alexa-app": "^4.1.0"`

**Comment by dblock** [comment]
Go through the steps from scratch that @lazerwalker did, what is different?

**Comment by cpup22** [comment]
I got it working. Problem was I had a linked file that was using Mongoose promises and a bluebird (what @lazerwalker suggested!!) import was causing a conflict. Thanks all for the pointers... sorry for the issue.
