### ISSUE TITLE
HTTPS GET Help

### ISSUE THREAD

**Issue by NovaGL** [alexa-js/alexa-app#285]
I need some help, Async gets me all confused sync I am a novice in Node-Red.

I just want Alexa to say something it receives from a HTTPS Call. I am using (https://github.com/alexa/alexa-cookbook/blob/master/external-calls/httpsGet/src/index.js) as an example but I don't know how to adapt it to use Alexa app. Any help would be great.

Not sure if this is right

```
alexaApp.intent('Test', {},            
  function(req, res) {   
    httpsGet(myRequest,  (myResult) => {
                console.log("sent     : " + myRequest);
                console.log("received : " + myResult);
                this.res.say('The population of ' + myRequest + ' is ' + myResult);
                this.emit(':responseReady');
            }
        );
    });

````

The console log shows the correct info. But it goes wrong from there.

**Comment by lazerwalker** [comment]
If you're trying to handle an intent asynchronously, you'll need the code that fires off your network request to use promises rather than a callback function, and have the intent function return that promise. Without that, the library won't know to wait for your asynchronous call to return before sending a response to Amazon.

Without knowing where your `httpsGet` function is coming from, you'd want a Promise-based version to maybe look something like this:

```js
alexaApp.intent('Test', {},            
  function(req, res) {   
    return httpsGet(myRequest).then((myResult) => {
                console.log("sent     : " + myRequest);
                console.log("received : " + myResult);
                res.say('The population of ' + myRequest + ' is ' + myResult);
            })
        );
    });
```

(You'll notice I also removed the `this` from `res.say`. I also removed the `this.emit` call — that's something that's part of the official Alexa JS SDK, but doesn't exist / isn't necessary in the `alexa-app` library)

Hope that's helpful!

**Comment by NovaGL** [comment]
Thanks for that @lazerwalker. I think you have too many closing brackets.

I just copied the alexa example so the function is the same as what I linked to.

So it looks like that needs to be fixed too?

``` javascript
function httpsGet(myData, callback) {

    // GET is a web service request that is fully defined by a URL string
    // Try GET in your browser:
    // https://cp6gckjt97.execute-api.us-east-1.amazonaws.com/prod/stateresource?usstate=New%20Jersey


    // Update these options with the details of the web service you would like to call
    var options = {
        host: 'cp6gckjt97.execute-api.us-east-1.amazonaws.com',
        port: 443,
        path: '/prod/stateresource?usstate=' + encodeURIComponent(myData),
        method: 'GET',

        // if x509 certs are required:
        // key: fs.readFileSync('certs/my-key.pem'),
        // cert: fs.readFileSync('certs/my-cert.pem')
    };

    var req = https.request(options, res => {
        res.setEncoding('utf8');
        var returnData = "";

        res.on('data', chunk => {
            returnData = returnData + chunk;
        });

        res.on('end', () => {
            // we have now received the raw return data in the returnData variable.
            // We can see it in the log output via:
            // console.log(JSON.stringify(returnData))
            // we may need to parse through it to extract the needed data

            var pop = JSON.parse(returnData).population;

            callback(pop);  // this will execute whatever function the caller defined, with one argument

        });

    });
    req.end();

}

```

**Comment by lazerwalker** [comment]
Yeah, that seems pretty reasonable!

If that's giving you trouble, you might want to investigate pre-existing node libraries that provide a Promise-based API to make HTTP requests, such as https://github.com/request/request-promise (you'll find tons more at npmjs.com, I haven't used that one specifically).

You may also want to check out the async section of the readme for this project: https://github.com/alexa-js/alexa-app#asynchronous-handlers-example. The README in general is likely to be more useful to you than Amazon's alexa-cookbook examples, as `alexa-app` operates fairly differently from the official Alexa JS SDK.

**Comment by NovaGL** [comment]
Thanks. Don't really understand your async examples but doesn't really matter.

I am trying to make my own Alexa Sonos skill which could be adapted to control any music system that provides metadata.

This particular function is used for getting the now playing info.
I will also adapt it to get the favorites of a player, but that's the next step.

It will never be released as it's for private use but hopefully I can give the source out so people can do their own stuff if it ever gets to that level.
