### ISSUE TITLE
conversation example help

### ISSUE THREAD

**Issue by NovaGL** [alexa-js/alexa-app#289]
I was wondering if you could help. I have this intent (not complete yet)
Which when complete will get the location and prompt to play the station.

I want it to load StationIntent if they respond yes.
How would I go about doing that?

Thanks 
``` Javascript
alexaApp.intent("AMAZON.LocationIntent", {
    "slots": {},
    "utterances": []
  },
  function(request, response) {
    var station = "X";
    var locationOutput = "You are in X, your nearest station is " + station + ". Would you like to play it?";
    var reprompt = "Would you like to play it?";
    response.say(locationOutput).reprompt(reprompt).shouldEndSession(false);
});
```

**Comment by dblock** [comment]
Alexa doesn't quite have a "conversation" concept, so you have to keep state around, possibly in the session to know that you want to invoke a particular action following a "yes". I do this in https://github.com/dblock/amerika/blob/master/functions/amerika/index.js#L55 where at some point the skill asks you "Would you like to make America great again?" and if you say "yes" to it it will invoke the `AmerikaIntent`. It's cheating, but that works.

I'll close this, but feel free to ask more questions!

**Comment by NovaGL** [comment]
Thanks but I don't want someone to just say yes at the beginning.

I was thinking about state management

https://youtu.be/RrDY009pU44

Is there any way to do it?

**Comment by dblock** [comment]
Sounds like a good solution.

**Comment by apanazzolo** [comment]
Ok, thanks. Which is the syntax to in the alexa-app framework to have multiple mandatory slots in the same utterance? I'm using this one
app.intent("BillIntent", {
	"dialog": {
	      type: "delegate",
	},
    "slots": {
      "Month": "AMAZON.Month",
      "Energy": "Energy"
    },
    "utterances": [
      "{-|Month}",
      "{-|Energy}"
    ]
  },
