### ISSUE TITLE
AVS to one skill only

### ISSUE THREAD

**Issue by NovaGL** [alexa-js/alexa-app#290]
Not sure if this is the right place, but one of the skills I am making using this I want to integrate into an existing iOS\Android app.

The problem is I just want that skill to work nothing else. Is that possible?

**Comment by dblock** [comment]
What do you mean by "that skill to work"?

**Comment by NovaGL** [comment]
It is probably not possible. Say your app is a trivia app.

Clicking the microphone icon would allow you to speak to Alexa and replicate the trivia game using an Alexa skill.

I believe this is not possible as you would need the skill to be enabled for that user. But curious to know if anyone had thought of this use case.

If you don't understand I can try to explain it further, if not and you feel it's not possible just close this issue.

**Comment by lazerwalker** [comment]
I haven't looked too closely at AVS, but I don't believe there's an API that exists at a layer between "here's an Alexa Skill that runs on an Alexa device" and "here are low-level primitives to train your own language model".

You might want to poke at the Microsoft Bot Framework. The tooling they provide to create Cortana Skills are fairly similar to Alexa, but they do provide enough access across all levels of abstraction that you might be able to deploy a voice-enabled iOS app in that way.

**Comment by NovaGL** [comment]
Interesting, thanks. So that would do iOS and Android.

I am not a real coder just looking at commericalising Alexa and thought this might be a way
