### ISSUE TITLE
Session attributes are not sending to alexa

### ISSUE THREAD

**Issue by shivamgupta211** [alexa-js/alexa-app#295]
Hi everyone, i am new to alexa-app and really enjoying working with it. Right now i am facing an issue, please help me out.

I am trying to set the session attribute using one or both below methods ,
`request.getSession().set('name', 'xyz')`
`response.session('age','zyx')`
`response.say('this is again')`
& I have double checked this by console the `response` object and it shows the newly added session attributes
but somehow when using, `.say()` method is not sending the session attributes as i have checked in the alexa testing console.

Any suggestion? Need help!

**Comment by dblock** [comment]
Are you using `shouldEndSession` as well? Build a test case next.

**Comment by shivamgupta211** [comment]
thank you @dblock for respndin.
Yes i am using the shouldEndSession(false),

**Comment by shivamgupta211** [comment]
Any suggestions? Need help! @dblock

**Comment by lazerwalker** [comment]
Do you have a more complete example, maybe some example code or a test case one of us can run?

One likely thing to check: is any of this happening asynchronously? It's fairly common to run into issues where you're not returning the right promise, and the response is sent to Amazon before you're finished with your logic.

**Comment by dblock** [comment]
If you write a spec that reproduces the problem I can try to help.

**Comment by shivamgupta211** [comment]
@lazerwalker thanks for the response. Your opinion was correct, i was sending the data to amazon before i finish with my logic, that's why the error occurred. once again thanks.
