### ISSUE TITLE
Possible to deploy on AWS lambda funciton

### ISSUE THREAD

**Issue by apanazzolo** [alexa-js/alexa-app#298]
Hi,
il possible to deploy the applications built using alexa-app framework into AWS lambda?
Thanks

**Comment by dblock** [comment]
Yes. The https://github.com/alexa-js/alexa-app-server project might make it easier.

Live coded and deployed to Lambda: http://code.dblock.org/2017/02/16/building-a-simple-alexa-skill-live-code.html
