### ISSUE TITLE
Maintain dialog alive without activate alexa every time

### ISSUE THREAD

**Issue by apanazzolo** [alexa-js/alexa-app#299]
Hi, I want know if this scenario is feasible with alexa-app framework. (I've implemented with delegate until the second alexa response)
User: "Alexa ask <myskill> how much is my gas bill"
Alexa:"Please tell me which month"
User:"March"
Alexa:"Your gas bill of Mach is 33$"
You:"Is greater or less than previous month?"
Alexa:"It's greater!"

**Comment by dblock** [comment]
Related? Dups? #289 #196

**Comment by apanazzolo** [comment]
Ok thanks!
There is a way to execute an intent only if I'm in a particular context? I.e. if I ask to my skill info about my gas bill and after I ask if there are suggestions about cost saving, the cost saving intent can be provided only if I'm in the dialog mode and I've asked  previously about gas bill?

**Comment by lazerwalker** [comment]
There's no way at the library level to only conditionally execute an intent.

What most folks do, and what Amazon themselves recommend, is do your own state management from within your own handlers. At a trivial level, this could be as simple as:

```js
app.intent("DoAThingOnlyIfStateIsFoo", {}, (req, res) => {
  if (req.getSession().get('state') === "Foo") { // Set in a different intent
    // Do the thing!
  } else {
    res.say("I'm sorry, I didn't understand you")
  }
})
```

For more complex skills, I've personally found success modeling a more formal state machine, with intent handlers capable of causing state machine transitions and executing separate state machine handler functions as appropriate.

**Comment by apanazzolo** [comment]
ok thank you! another thing. I've developed a skill that has slots mandatory, but although they are mandatory and of a specific type (AMAZON.Number or AMAZON.Month) if I say "CAT" for a month alexa go ahead!! There is a way to delegate the check of response to Alexa platform? It works also for custom slots?
Thanks

**Comment by lazerwalker** [comment]
Yeah, there's sadly no good way to do that, it's a problem on Amazon's end that they'll happily trigger an intent with nonsense slot values.
