### ISSUE TITLE
Switch optionalDependencies to peerDependencies

### ISSUE THREAD

**Issue by nick-woodward** [alexa-js/alexa-app#300]
### Description

This package currently has `typescript` and `dtslint` listed as `optionalDependencies`.

I do not use typescript in my lambda functions and have no intention of doing so. 

However because this package was listed as an `optionalDependency` rather then a `peerDependency` its causing me to zip it up with the rest of my dependencies. (also increasing my artifact by ~10MB)

### Reference

https://github.com/alexa-js/alexa-app/blob/a32fc071d6fa6baba48b9cdf3409bb0c58c85e1c/package.json#L63-L66

**Comment by lazerwalker** [comment]
Ah, good catch!

As validating the types is part of running the tests, it seems to me these should actually be in `devDependencies` rather than `peerDependencies`. They definitely don't belong in `optionalDependencies`, though!
