### ISSUE TITLE
verifier not returning the right response code

### ISSUE THREAD

**Issue by sbeatz** [alexa-js/alexa-app#304]
my skill got removed from the alexa skill store cause the cert verification is not working properly

now i checked the verification manually and the only difference i found compared to the Amazon Docs is that the verifier returns 401 instead of 400...
still waiting for a response from Amazon - but did anyone else have this issue already?

**Comment by tejashah88** [comment]
Are you using express.js to host the skill. If so, the middleware for parsing it was recently updated and that could be the problem. @mreinstein Has there been any breaking changes to your alexa-verifier that should be addressed?

**Comment by sbeatz** [comment]
using both old and new(1.0.0) - old on live and new on dev - both return 401 when the verifier fails
can change that easily myself, but was just curious if anyone else is facing that kind of issues with amazon

**Comment by tejashah88** [comment]
Try changing it to 400, and submit it for certification again. If it succeeds, that means it's the middleware's fault. Otherwise there maybe be something else wrong with your setup.

**Comment by sbeatz** [comment]
feedback after recertification: changed it to 400 and got certified again

**Comment by tejashah88** [comment]
@sbeatz Just released a patch (v1.0.1) which now returns a 400 on any error.

**Comment by dblock** [comment]
This was https://github.com/alexa-js/alexa-verifier-middleware/commit/38ec0c37b15c75ff93cbb650a27c4dda48b62457 and https://github.com/alexa-js/alexa-verifier-middleware/commit/c4d82c6e5f9d7dcb2362a3c6a4c2492d5d7e588f.
