### ISSUE TITLE
Release 4.2.1

### ISSUE THREAD

**Issue by matt-kruse** [alexa-js/alexa-app#309]
Please release 4.2.1, so new projects can use the askcli() feature. Thanks.

**Comment by dblock** [comment]
You're the OG on this project Matt and you have all access to do a release! Go for it.

**Comment by dblock** [comment]
Updated release instructions in https://github.com/alexa-js/alexa-app/blob/master/RELEASING.md

**Comment by dblock** [comment]
@kobim Care to do a release? Follow the instructions above please.

**Comment by matt-kruse** [comment]
I need to catch up a bit to make sure that I follow the procedures you have in place now. I'm not used to adjusting type definitions or test cases. ;) 

I'm working off a local copy now and make a few changes to support a new API that is coming. I won't be able to commit until the API is public, but if I get chance to do a release before then I will.

**Comment by kobim** [comment]
@matt-kruse - anything you want to add to this release, or can I go ahead and publish it?

**Comment by dblock** [comment]
Go ahead @kobim!

**Comment by kobim** [comment]
Done!

**Comment by matt-kruse** [comment]
Thank you! I am adding code for upcoming API's but didn't have anything to contribute for this release. But having this update on npm will be helpful, thanks!
