### ISSUE TITLE
Question: Is it possible to use this with Serverless

### ISSUE THREAD

**Issue by chearmstrong** [alexa-js/alexa-app#311]
If so, do you have a basic example to get up an running?

**Comment by lazerwalker** [comment]
Hi! There's a section in the README with an example of using AWS Lambda for serverless: https://github.com/alexa-js/alexa-app#aws-lambda

I believe https://github.com/artsy/elderfield is also an example of a functioning Alexa skill using this library that's currently deployed on Lambda.

If you're talking about serverless solutions other than Lambda, that should be totally doable, but you're probably going to be a bit more on your own.

**Comment by chearmstrong** [comment]
Hi @lazerwalker - Yeah, I've used that implementation before. However, I was referring to the Serverless framework - https://serverless.com/

I can have play around to see if I can get this working on my own, I just wasn't sure about it as Serverless' example just uses the alexa-sdk directly.

**Comment by matt-kruse** [comment]
What advantage would Serverless give you over the ASK CLI?
I've always been curious about Serverless but the barrier to entry always felt a little too high. I got lost in the details.

**Comment by tejashah88** [comment]
The idea of Serverless is so that you don't have to be vendor-locked into a specific provider. With ask-cli, you are pretty much forced to use AWS Lambda as the main location for your skill logic.

**Comment by matt-kruse** [comment]
Yeah, that I get for general services. For Alexa Skills, you're already swimming in the Amazon ecosystem. I don't see any reason to use a different cloud provider. Just to torture yourself and make things harder? ;)

**Comment by tejashah88** [comment]
Personally, I like the flexibility of using any cloud provider for my functions, especially if AWS Lambda has certain features missing that I'd like to have.

**Comment by kobim** [comment]
I've put some examples on [alexa-serverless-test](https://github.com/kobim/alexa-serverless-test), which basically shows you just need to wrap `alexaApp.request` with the provider-specific implementation. This has already been done for [Express](https://github.com/alexa-js/alexa-app#express) and [AWS Lambda](https://github.com/alexa-js/alexa-app#aws-lambda) (as @lazerwalker suggested earlier).

I guess you would like to see something like the [lambda handler](https://github.com/alexa-js/alexa-app/blob/v4.2.0/index.js#L737) for the other providers?
