### ISSUE TITLE
app.schemas.skillBuilder()

### ISSUE THREAD

**Issue by MatthewPringle** [alexa-js/alexa-app#312]
Im not sure how to generate the Skill Builder Syntax generator.

Could someone please help me out with this?

**Comment by lazerwalker** [comment]
Hi! Can you be a little more clear on what issues you're having? Happy to provide some guidance, but I need to know more about what's going on.

**Comment by MatthewPringle** [comment]
Im using Amazon's Skill Builder Beta in their Alexa Developer website linked to Amazon Lambda to run the skill.

I have written a small app in alexa-app and uploaded it to Lambda. It runs locally fine but I understand I need to generate the Schema and Utterances.

As I am using Amazon's Skill Builder I read I needed to use app.schemas.skillBuilder() to generate the required Json file.

How do I do that? If I add the line to index.js it generates the following error

TypeError: Cannot read property 'skillBuilder' of undefined

**Comment by lazerwalker** [comment]
Can you confirm which version of the library you’re using? Support for the skill builder scheme is still fairly new, and that error message seems consistent with what I’d expect if you tried to use it on an earlier version of the lib before we had multiple output schemas.

**Comment by MatthewPringle** [comment]
Yes updating solved the error message. The sample file I copied from somewhere contained an older version.

Thanks for the help.
