### ISSUE TITLE
Which is correct DisplayElementSelected or DisplayElementSelectedFunc?

### ISSUE THREAD

**Issue by hidesuke** [alexa-js/alexa-app#318]
Currently I am working for EchoSpot functionality. I found that the README says implement `app.displayElementSelected`, however it does not work. So I implemented `app.displayElementSelectedFunc` instead of `app.app.displayElementSelected` then it works.

So, I think `app.displayElementSelectedFunc` works. However reading the test code, test code uses `app.displayElementSelected`.

Is there any issues around test code?

Thanks!

**Comment by dblock** [comment]
Probably, please contribute!

**Comment by hidesuke** [comment]
Hey, it was my misunderstanding.

I set `app.displayElementSelected = (req, res) => {...}` like this. But the correct way is `app.displayElementSelected((req, res) => {...});`.

Sorry for bothered you.
