### ISSUE TITLE
Missing progressive response support

### ISSUE THREAD

**Issue by malikov** [alexa-js/alexa-app#326]

**Comment by malikov** [comment]
Basically I needed the requestId in order to post my progressive response to the amazon api endpoint. But when I was debugging I looked at the alexa-app source code and realise that the request.requestId filed was missing. Could this be added ? 

See for further info : https://developer.amazon.com/docs/custom-skills/send-the-user-a-progressive-response.html

**Comment by malikov** [comment]
Nevermind I found it. Everything else is in the data attribute

**Comment by matt-kruse** [comment]
Yes, to be clear, inside alexa-app, request is a custom object. The data attribute of the request contains the raw request exactly as sent from Alexa to the skill.
