### ISSUE TITLE
Is there a way to trap unhandled intents?  

### ISSUE THREAD

**Issue by roschler** [alexa-js/alexa-app#337]
I got my first round trip working between my test Alexa skill and my alexa-app handler code.  Unfortunately, the intent I defined in the management console was not one I had a handler for since it was a custom intent name I created.  I saw this in the management console test results:

    {
	  "version": "1.0",
	  "response": {
	    "directives": [],
	    "shouldEndSession": true,
	    "outputSpeech": {
	      "type": "SSML",
	      "ssml": "<speak>Sorry, the application didn't know what to do with that intent</speak>"
	    }
	  },
	  "sessionAttributes": {}
	}

Is there a way to define an error handler function to catch unhandled _intents_ that will be fired if an INTENT is received?  If it weren't for that result above, I wouldn't have known about the unhandled INTENT since I didn't see anything in the Console/Log window of my Node.JS IDE.

**Comment by tejashah88** [comment]
Recently, Amazon has released [a new intent](https://developer.amazon.com/docs/custom-skills/standard-built-in-intents.html#fallback) for the purpose of handling phrases that shouldn't be handled via `AMAZON.FallbackIntent` (only for US English). As for handling unimplemented intents, alexa-app will throw a "NO_INTENT_FOUND" error and you can customize the error message [here](https://github.com/alexa-js/alexa-app#customizing-default-error-messages).
