### ISSUE TITLE
Drop node versions 1-4 and add support for node 9 and 10

### ISSUE THREAD

**Issue by tejashah88** [alexa-js/alexa-app#355]
Since node 1 to 3 aren't used as much and with the recent announcement of node 4.x reaching end of life, I think it would make sense to not include it for future travis builds. On the other hand, we should add testing for node versions 9 and 10. What do you guys think?

**Comment by tejashah88** [comment]
@alexa-js

**Comment by dblock** [comment]
I think adding new versions is a no brainer. 

I would drop support only if it's in the way, eg. when fixing or adding something and that breaks old versions. If it costs nothing to maintain my vote is to keep it, avoid pain for users who're slower to upgrade.
