### ISSUE TITLE
.reprompt() not concatenating

### ISSUE THREAD

**Issue by andrewjhunt** [alexa-js/alexa-app#359]
Current code:
      this.response.response.reprompt.outputSpeech.ssml = SSML.fromStr(str, this.response.response.reprompt.outputSpeech.text);

Correction
      this.response.response.reprompt.outputSpeech.ssml = SSML.fromStr(str, this.response.response.reprompt.outputSpeech.ssml);

Need to reference the .ssml variable (instead of .text)

**Comment by dblock** [comment]
Please pull request a test + fix.

**Comment by andrewjhunt** [comment]
See pull request #364 
https://github.com/alexa-js/alexa-app/pull/364

**Comment by andrewjhunt** [comment]
Is it a bug? 

The API doc is not specific but it would be helpful if .reprompt() concatenated just like .say(). And the code looks like it is written to concat but just references the wrong var. But, the unit tests might suggest the current behavior is intentional.
