### ISSUE TITLE
How to emit/called existing intend

### ISSUE THREAD

**Issue by mudaser-caremerge** [alexa-js/alexa-app#363]
Suppose i have following attend

```
app.intend('callme', {slots: {}, utterances: [], (req, res) => { res.say(`i m called`)});

```

how i can call this intend from another intend i.e.,

```
app.intend('other', {slots: {}, utterances: [], (req, res) => {  });

```

**Comment by kobim** [comment]
#374 just [resolved that](https://github.com/alexa-js/alexa-app#router)!
The new version will be released by the end of this weekend.

**Comment by mudaser-caremerge** [comment]
Thank you so much!
