### ISSUE TITLE
Cannot get directive display to work in Alexa skill. 

### ISSUE THREAD

**Issue by secondsea** [alexa-js/alexa-app#382]
In the alexa simulator i get the error
there was   a problem with the requested response

handle(handlerInput) {
    const factArr = data;
    const factIndex = Math.floor(Math.random() * factArr.length);
    const randomFact = factArr[factIndex];
    const speechOutput = GET_FACT_MESSAGE + randomFact;

    return handlerInput.responseBuilder
      .speak(speechOutput)
     .withSimpleCard(SKILL_NAME, randomFact)
      .addRenderTemplateDirective({
       type:'BodyTemplate1',
       token:'token1',
      backButton:'HIDDEN',
       backgroundImage:backgroundImagePath,
       title:SKILL_NAME,
      textContent:{
          type:'RichText',
          text:randomFact
      }
        
      })
         .getResponse();
  },
};

**Comment by matt-kruse** [comment]
This looks like it's using the SDK, not alexa-app.

**Comment by secondsea** [comment]
could you elaborate? I'm really new at this.
