### ISSUE TITLE
Not able to use alexa-app

### ISSUE THREAD

**Issue by FunnyDevs** [alexa-js/alexa-app#383]
Hi! I'm trying to use alexa-app instead of ask-sdk with express. With ask-sdk i'm able to create an express server that intercepts all post request and forward the requests to the alexa handler; i am able to use it in localhost and test public with ngrok.
With alexa-app, i cloned the express sample repository but when i send any request no callback was called.
What do i do wrong?

Thanks

**Comment by dblock** [comment]
Please try the samples and otherwise share code that doesn't work and we'll try to help you.

I'll close this for now, but add more info and we can reopen if there's an issue.

**Comment by FunnyDevs** [comment]
Ok, i have resolved with alexa-app-server. Thank you
