### ISSUE TITLE
request.userId returning the wrong user

### ISSUE THREAD

**Issue by matthewturner** [alexa-js/alexa-app#387]
Hi,
I've added another user as a beta tester of my skill but when I use `request.userid` to identify the incoming request, it keeps returning my own userid.
Is there anything obvious I'm doing wrong?
Thanks,
Matt

**Comment by dblock** [comment]
Probably not, unlikely a library problem. Let us know what you find.

**Comment by matthewturner** [comment]
Thanks for the response. As you said it's not a library problem - it's completely unrelated and I won't bother you with the details!

**Comment by dblock** [comment]
@matthewturner Bother us with details! For the next person googling this. Thanks.
