### ISSUE TITLE
Issues testing locally the Skill: alexa-app + express + ngrok

### ISSUE THREAD

**Issue by gperezcarellan** [alexa-js/alexa-app#403]
Hi, I just want to test faster my code so I tried to run local server using ngrok tunneling. I have tried with a REST client and it's working fine, the problem that I have is that after configuring my skill and triggering some intents  I can see I receive a POST request in ngork http request history but the response is 404 Not Found. Although I can capture the request making the route express.post(), so as far as I can understand there is some kind of problem that POST request made by my skill when tunneling with ngrok and running server local cant be "recognized" as intents so there is no intent that can handle the request. What could be the problem, what can I try? Thanks in adavance.

ngrok version 2.3.35
alexa-app version  4.2.3

**Comment by gperezcarellan** [comment]
Solved. I just forgot to include full URL when using ngrok forwarding, for instance if you created an instance of your app like `var app = new alexa.app('test');` you should include in your skill configuration as endpoint {YOUR_NGROK_URL}/test instead of just {YOUR_NGROK_URL}

**Comment by dblock** [comment]
If the docs can be improved, please PR!
