### ISSUE TITLE
Smart Home API Integration

### ISSUE THREAD

**Issue by briananderson1222** [alexa-js/alexa-app#63]
I may have not dug into this enough, but just curious if there are any plans for having any sort of top level provider/configurator for controlling the types skills request/responses this framework uses. I know right now this works great with custom skills, but i'd imagine in a similar way we could abstract away the request/response contract for other types of skills as they become made available by Amazon.

https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/smart-home-skill-api-reference

Thoughts?

**Comment by dblock** [comment]
Would take pull requests.

**Comment by mreinstein** [comment]
@briananderson1222 based on what I've seen in the smart home skill reference materials, the api is drastically different from alexa skills.

I prefer modules that are small and do a limited number of things. I'd prefer `alexa-app` to be kept small and specific. 

If you want to come up with a new abstraction that encapsulates smart home skills, sounds like an opportunity for a new module. :) `alexa-smart-home-skill` perhaps?
