### ISSUE TITLE
Router Add-on

### ISSUE THREAD

**Issue by nickcoury** [alexa-js/alexa-app#94]
I'm really happy to see there are some new maintainers breathing life into this! I find this library's design far more usable than Amazon's official library.

I started writing a router ([alexa-app-router](https://github.com/nickcoury/alexa-app-router)) for use in my own project [Mountain Top](https://github.com/nickcoury/mountain-top), on GitHub and published in the Skills store.

I wanted to see if others would find use in this kind of router.  I find it far more usable than intents as the main Alexa paradigm.  I built it to require minimal configuration, and envision supporting route parameters and more complex use cases in future versions.

As of now, it's bolt-on ready for `alexa-app` and doesn't alter the core library behaviors.  I plan to continue it solely as an add-on now, though if many people find it useful a link in the official README could give it some visibility.  If it proves popular and would fit well in the main library, I'd be happy to donate the code, otherwise I don't think there's a big downside to keeping it separate.

**Comment by dblock** [comment]
It looks great! You should definitely PR a link with an explanation into README.

This is a +1 in favor if an alexa-app org in which we could move some of these related projects like alexa-app-server, router, etc.

**Comment by nickcoury** [comment]
Great, I'll clean up the code and add some tests, then PR it over here.

**Comment by dblock** [comment]
https://github.com/alexa-js

**Comment by dblock** [comment]
Closing this, thanks for the router @nickcoury!
